# 넘파이
넘파이의 배열 클래스인 numpy.array에는 편리한 메소드가 많이 준비되어있어 딥러닝을 구현할 때 이 메소드들을 이용한다.

In [ ]:
# 넘파이 가져오기
import numpy as np

```import numpy as np```는 numpy를 np라는 이름으로 가져오라는 뜻이다.



**넘파이 배열**을 만들 때는 np.array() 메소드를 이용한다. np.array()는 파이썬의 리스트를 인수로 받아 넘파이 라이브러리가 제공하는 특수한 형태의 배열(numpy.ndarray)을 반환합니다.

In [ ]:
x = np.array([1.0, 2.0, 3.0])
print(x)
print(type(x))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [ ]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x+y)  # 원소별 덧셈
print(x-y)
print(x*y)  # 원소별 곱셈
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


주의할 점

*   x와 y의 원소 수가 같다
*   x와 y의 원소 수가 다를 경우 오류 발생
*   x와 y의 원소 수가 같다면 산술 연산은 각 원소에 대해서   행해진다.
---

'원소별'이라는 말은 영어로 element-wise라고 한다.

---
'원소별 곱셈'은 element-wise product라고 한다

---
넘파이 배열은 원소별 계산뿐만 아니라 넘파이 배열과 수치 하나(스칼라값)의 조합으로 된 산술 연산도 수행할 수 있다. 이 경우 스칼라값과의 계산이 넘파이 배열의 원소별로 한 번씩 수행된다. 이 기능을 **`브로드캐스트`**라고 한다







In [ ]:
x = np.array([1.0, 2.0, 3.0])
x / 2.0

array([0.5, 1. , 1.5])

# 넘파이 N차원 배열
넘파이는 1차원 배열뿐만 아니라 다차원 배열도 작성할 수 있다. 예를 들어 2차원은 다음처럼 작성함


In [ ]:
A = np.array([[1,2], [3,4]])
print(A)
print(A.shape)
print(A.dtype)

[[1 2]
 [3 4]]
(2, 2)
int64


2x2의 A라는 행렬 작성. 

*   행렬의 형상은 shape
*   행렬에 담긴 원소의 자료형 dtype

이어서 행렬 산술 연산




In [ ]:
B = np.array([[3,0],[0,6]])
print(A+B)
print(A*B)

[[ 4  2]
 [ 3 10]]
[[ 3  0]
 [ 0 24]]


형상이 같은 행렬끼리면 행렬의 산술 연산도 대응하는 원소별로 계산된다.행렬과 스칼라값의 산술 연산도 가능하다. 이때도 배열과 마찬가지로 브로드캐스트 기능이 작동한다

In [ ]:
print(A)
print(A*10)

[[1 2]
 [3 4]]
[[10 20]
 [30 40]]


# NOTE
넘파이 배열은 N차원 배열을 작성할 수 있다. 1차원 배열, 2차원 배열, 3차원 배열처럼 원하는 차수의 배열을 만들 수 있다는 뜻이다. 수학에서는 1차원 배열은 `벡터`, 2차원 배열은 `행렬(matrix)`이라고 부른다. 또 벡터와 행렬을 일반화한 것을 `텐서`라 한다.

# 브로드캐스트


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([10,20])
A*B

array([[10, 40],
       [30, 80]])

# 원소 접근

In [ ]:
X = np.array([[51, 55], [14, 19], [0,4]])
print(X)
print(X[0])     # 0행
print(X[0][1])  # (0,1) 위치의 원소

[[51 55]
 [14 19]
 [ 0  4]]
[51 55]
55


In [ ]:
for row in X:
  print(row)

[51 55]
[14 19]
[0 4]


In [ ]:
X = X.flatten()       # X를 1차원 배열로 변환(평탄화)
print(X)
X[np.array([0,2,4])]  # 인덱스가 0, 2, 4인 원소 얻기

[51 55 14 19  0  4]


array([51, 14,  0])

이 기법을 응용하면 특정 조건을 만족하는 원소만 얻을 수 있다. 예컨대 다음과 같이 ```배열 X에서 15 이상인 값만``` 구할 수 있다

In [ ]:
print(X>15)
print(X[X>15])

[ True  True False  True False False]
[51 55 19]


넘파이 배열에 부등호 연산자를 사용한 결과는 ```bool 배열```
이다. 여기에서는 이 bool 배열을 사용해 배열 X에서 True에 해당하는 원소, 즉 값이 15보다 큰 원소만 꺼낸다


# NOTE


*   파이썬 같은 동적 언어는 C나 C++같은 정적 언어(컴파일 언어)보다 처리 속도가 늦다
*   무거운 작업을 할때는 C/C++로 작성한 프로그램을 쓰는 편이 좋다
*   파이썬에서 빠른 성능이 요구될 경우 해당 부분을 C/C++로 구현한다.
*   이럴 때 파이썬은 C/C++로 쓰인 프로그램을 호출해주는 '중개자'역할을 한다.
*   넘파이도 주된 처리는 C/C++로 구현함. 그래서 성능을 해치지 않으면서 파이썬의 편리한 문법을 사용할 수 있다

